[unstable]
# cross compile core library for custom target
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
# points to file in project root
target = "x86_64-unknown-none.json"


[alias]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
